"""001 initial

Revision ID: 5107d4cfa65d
Revises: 
Create Date: 2026-04-25 16:42:52.640787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5107d4cfa65d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('in_progress','completed')", name='idemkey_state_check'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('outbox_unpublished_idx', 'outbox_events', ['published_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('processed_webhooks',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'event_id')
    )
    op.create_table('statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('virtual_iban', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('source_ref', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('top_up','fund_transfer')", name='statements_kind_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'source_ref', name='statements_kind_source_ref_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statements')
    op.drop_table('processed_webhooks')
    op.drop_index('outbox_unpublished_idx', table_name='outbox_events', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('outbox_events')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
